service: sosajd
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.9

functions:
  function_one:
    handler: handler.function_one
    events:
      - httpApi:
          path: /one
          method: get
  function_two:
    handler: handler.function_two
    events:
      - httpApi:
          path: /two
          method: get
